### ISSUE TITLE
round2 in CalculatePCA_pops_plot.m

### ISSUE THREAD

**Issue by JauntyJJS** [eelhaik/PCA_critique#10]
Hi,

I was running some codes in the `Main_PCA_Pops.m` file and had some issues running the `CalculatePCA_pops_plot` function.

It gives the following error message

```
Unrecognized function or variable 'round2'.

Error in CalculatePCA_pops_plot (line 57)
    xlabel([PC1_label num2str(round2(10000*pcvars_exp(1),2)/100) '%']);
```

Is `round2` a customized function ? I am only familiar with `round`.

Kindly clarify. Thank you

**Comment by eelhaik** [comment]
Hi, I uploaded it to github

https://github.com/eelhaik/PCA_critique/blob/main/round2.m

 

Best,

Eran

 

 

From: Jeremy Selva ***@***.***> 
Sent: Monday, November 28, 2022 8:10 AM
To: eelhaik/PCA_critique ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [eelhaik/PCA_critique] round2 in CalculatePCA_pops_plot.m (Issue #10)

 

Hi,

I was running some codes in the Main_PCA_Pops.m file and had some issues running the CalculatePCA_pops_plot function.

It gives the following error message

Unrecognized function or variable 'round2'.
 
Error in CalculatePCA_pops_plot (line 57)
    xlabel([PC1_label num2str(round2(10000*pcvars_exp(1),2)/100) '%']);

Is round2 a customized function ? I am only familiar with round.

Kindly clarify. Thank you

**Comment by JauntyJJS** [comment]
Thank you. I am able to proceed.
