### ISSUE TITLE
load_list and num2str_comma in Main_PCA_Pops.m

### ISSUE THREAD

**Issue by JauntyJJS** [eelhaik/PCA_critique#11]
Hi,

I was running some codes in the Main_PCA_Pops.m file and had this error message when running section 11 Choice of markers.

```
Unrecognized function or variable 'num2str_comma'.
```

It seems that I need the code for this function as well. 
Sorry about that.

**Comment by eelhaik** [comment]
Sorry about that, uploaded it to github.

**Comment by JauntyJJS** [comment]
Thank you for the prompt response.  I need the code for another function called `load_list`  for MATLAB to read the `SNP_list.txt` file.

**Comment by eelhaik** [comment]
Uploaded to github

**Comment by JauntyJJS** [comment]
Thank you. I am able to run the `Main_PCA_Pops.m` script without any issues.

**Comment by eelhaik** [comment]
Excellent, thanks for letting me know.
