### ISSUE TITLE
Clarification on the database Lazaridis_1kg_AJ_full [Question]

### ISSUE THREAD

**Issue by JauntyJJS** [eelhaik/PCA_critique#12]
Hi,

I wish to ask some question to understand the dataset loaded ?
In the `Main_PCA_Pops.m` file,  loading the database using the `Load_Database_final` stores the genomic data into `Data_`

![image](https://user-images.githubusercontent.com/9066508/208363863-a5cd564e-8f80-4531-a084-bd89f59d3aa2.png)

I understand that `Data_` is a 5043 by 128568 numerical matrix.

May I clarify if the 5043 rows of `Data_` are the samples and the annotation for the samples can be found in `Labels` ?

As for the 128568 columns of `Data`, are they the gene name ?

**Comment by eelhaik** [comment]
May I clarify if the 5043 rows of Data_ are the samples and the annotation for the samples can be found in Labels ?

Yes

As for the 128568 columns of Data), are they the gene ?

Markers (SNPs), not genes.

 

From: Jeremy Selva ***@***.***> 
Sent: Monday, December 19, 2022 7:49 AM
To: eelhaik/PCA_critique ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [eelhaik/PCA_critique] Clarification on the database Lazaridis_1kg_AJ_full [Question] (Issue #12)

 

Hi,

I wish to ask some question to understand the dataset loaded ?
In the Main_PCA_Pops.m file, loading the database using the Load_Database_final stores the genomic data into Data_

 <https://user-images.githubusercontent.com/9066508/208363863-a5cd564e-8f80-4531-a084-bd89f59d3aa2.png> 

I understand that Data_ is a 5043 by 128568 numerical matrix.

May I clarify if the 5043 rows of Data_ are the samples and the annotation for the samples can be found in Labels ?

As for the 128568 columns of Data), are they the gene ?

**Comment by JauntyJJS** [comment]
Thank you for the information.

I believe the first column of the numerical matrix belong to `rs3094315`, the second column is `rs9442372` and so on.

![image](https://user-images.githubusercontent.com/9066508/208560493-a2b3c65a-8368-449f-af7f-397e6033f644.png)

**Comment by eelhaik** [comment]
Yes
