### ISSUE TITLE
Alternative places to upload large data files

### ISSUE THREAD

**Issue by JauntyJJS** [eelhaik/PCA_critique#13]
With regards to the issue that large file sizes cannot be uploaded to Github, beside storing the data in Google Drive, have you considered putting Lazaridis_1kg_AJ_full dataset in other places such as [figshare](https://figshare.com/) or [Open Science Framework](https://osf.io/) ?

**Comment by eelhaik** [comment]
Yeah, I put it here:

https://figshare.com/articles/dataset/PCA_critique_zip/21755864

 

 

From: Jeremy Selva ***@***.***> 
Sent: Tuesday, December 20, 2022 9:27 AM
To: eelhaik/PCA_critique ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [eelhaik/PCA_critique] Alternative places to upload large data files (Issue #13)

 

With regards to the issue that large file sizes cannot be uploaded to Github, beside storing the data in Google Drive, have you considered putting Lazaridis_1kg_AJ_full dataset in other places such as figshare <https://figshare.com/>  or Open Science Framework <https://osf.io/>  ?
