### ISSUE TITLE
Main_ColorStat in Main_PCA_Colors.m

### ISSUE THREAD

**Issue by JauntyJJS** [eelhaik/PCA_critique#4]
Hi,

I was trying to run the codes in Main_PCA_Colors.m inside the folder Main_PCA_Colors.m
At around line 193, I come across

```
Main_ColorStat(M, SCORE, 1, S)
```

I understand that it is a function. However, I do not know where is the location of this function and got this error message

```
Unrecognized function or variable 'Main_ColorStat'.
```

Is it possible to provide some guidance on where this function is called (which m file is used) ?

Thank you.

**Comment by eelhaik** [comment]
Thanks for letting me know, please check out [Matlab_code_V4.zip](https://github.com/eelhaik/PCA_critique/blob/main/Matlab_code_V4.zip).

**Comment by JauntyJJS** [comment]
Thank you. With the additional Main_ColorStat.m, things are able to run.
