### ISSUE TITLE
#12 Inferring individual ancestry not in Main_PCA_Colors.m

### ISSUE THREAD

**Issue by JauntyJJS** [eelhaik/PCA_critique#8]
Hi,

It is observed that the `Main_PCA_Colors.html` file in the `Main_PCA_Colors` folder have a section on `#12 Inferring individual ancestry`

![image](https://user-images.githubusercontent.com/9066508/204090772-8013ab55-9423-414d-8f1b-1a4734aac2d6.png)

However, the code is not presence in the `Main_PCA_Colors.m` file.

May I just copy and paste the code in the html to the `Main_PCA_Colors.m` file or has the section been removed for a good reason ?

**Comment by eelhaik** [comment]
You can copy it, not sure why it's missing.

**Comment by JauntyJJS** [comment]
Sure no problem. I am able to run the code from my end.
