### ISSUE TITLE
Database in Main_PCA_Pops.m

### ISSUE THREAD

**Issue by JauntyJJS** [eelhaik/PCA_critique#9]
Hi,

I was trying to run the codes in `Main_PCA_Pops.m` which uses the `Load_Database_final` function to load the Lazaridis_full dataset.

However, it seems that the dataset is not in this GitHub page.

Is the dataset accessible in another location ?

**Comment by eelhaik** [comment]
Github wouldn’t let me upload these files, which are really large.

I now copied them here

https://drive.google.com/drive/folders/1G9769_PyhZP0us4p48Vu-QWECQR2Oufi?usp=share_link

 

hopefully, its all there

 

 

 

From: Jeremy Selva ***@***.***> 
Sent: Sunday, November 27, 2022 8:48 AM
To: eelhaik/PCA_critique ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [eelhaik/PCA_critique] Database in Main_PCA_Pops.m (Issue #9)

 

Hi,

I was trying to run the codes in Main_PCA_Pops.m which uses the Load_Database_final function to load the Lazaridis_full dataset.

However, it seems that the dataset is not in this GitHub page.

Is the dataset accessible in another location ?

**Comment by JauntyJJS** [comment]
Thank you. I have managed to download it successfully.
